### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/colonel-kurtz#45]
Changes will be tracked to https://github.com/vigetlabs/colonel-kurtz/tree/v2.0.0-dev

### Todo

- [x] Increase test coverage to 100% before changes
- [x] Remove Editor Store (#48)
- [x] "section" block type
- [x] Drop Diode dependency (no singletons!)
- [x] Stores should not be singletons (#47)
- [x] Determine section editing UI (#44)
- [x] Implement section editing UI (#44)
- [x] Determine data migration strategy (#32)
- [x] Document data migration strategy (#32)
- [x] Data migration binary (#32)
- [ ] Add concept of meta data
- [x] Confirm React 0.13.0 compatibility (#46)
- [x] Maintain backwards compatibility with React 0.12.0
- [x] Eliminate use of context API
- [x] Complete CHANGELOG.MD
- [x] Remove uses of React Context API

**Comment by nhunzaker** [comment]
Closing this issue. I'll add one for meta data, but let's add some additional definition there.
